development:
  adapter: postgresql
  encoding: utf8
  database: evrone_challenge_development
  username:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: evrone_challenge_test
  username:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: evrone_challenge_production
  username:
  host: localhost
